-- world: 온라인 서점 "책숲" — fundamentals 코스의 모든 챕터가 공유하는 world
-- 스키마 정의. 시드는 seed.sql (generate_seed.py로 생성).

CREATE TABLE customers (
    customer_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             text    NOT NULL,
    email            text    NOT NULL UNIQUE,
    city             text    NOT NULL,
    signup_date      date    NOT NULL,
    marketing_opt_in boolean NOT NULL,
    birth_date       date                -- 선택 입력: NULL 허용 (5장)
);

CREATE TABLE books (
    -- 2~4장의 주 테이블: 모든 열 NOT NULL (NULL 도입 전 예제용)
    book_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title          text    NOT NULL,
    author         text    NOT NULL,
    category       text    NOT NULL,
    price          integer NOT NULL CHECK (price > 0),
    page_count     integer NOT NULL CHECK (page_count > 0),
    published_date date    NOT NULL,
    stock          integer NOT NULL CHECK (stock >= 0)
);

CREATE TABLE orders (
    order_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  integer NOT NULL REFERENCES customers (customer_id),
    order_date   date    NOT NULL,
    status       text    NOT NULL
                 CHECK (status IN ('배송준비', '배송중', '배송완료', '취소')),
    shipped_date date,               -- 아직 발송 전이면 NULL (5장)
    -- 발송된 상태(배송중·배송완료)일 때만 발송일이 있다 (world 정합성)
    CHECK ((status IN ('배송중', '배송완료')) = (shipped_date IS NOT NULL)),
    CHECK (shipped_date IS NULL OR shipped_date >= order_date)
);

CREATE TABLE order_items (
    order_id   integer NOT NULL REFERENCES orders (order_id),
    book_id    integer NOT NULL REFERENCES books (book_id),
    quantity   integer NOT NULL CHECK (quantity > 0),
    unit_price integer NOT NULL CHECK (unit_price > 0),  -- 주문 시점 단가 (단가×수량 계산 쌍, 6장)
    PRIMARY KEY (order_id, book_id)
);

CREATE TABLE reviews (
    review_id   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id     integer NOT NULL REFERENCES books (book_id),
    customer_id integer NOT NULL REFERENCES customers (customer_id),
    order_id    integer REFERENCES orders (order_id),
                -- 구매 인증 리뷰면 해당 주문, 아니면 NULL — NULL 허용 FK (7장 요구)
    rating      integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment     text,                -- 별점만 남긴 리뷰는 NULL (5장, COUNT 대비)
    review_date date    NOT NULL,
    UNIQUE (book_id, customer_id)    -- 한 사람이 한 책에 리뷰 하나
);
